# Server port for Render
server.port=${PORT:8080}

# Database (Aiven MySQL)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate config
spring.jpa.hibernate.ddl-auto=none

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog-master.xml
spring.liquibase.contexts=development,production

# Base URL for frontend
app.base-url=https://diplomski-ivory.vercel.app

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Upload folder (note: ephemeral on free Render instance)
app.upload.dir=uploads/lab-documents