package com.isa.enums;

public enum DoctorType {
    GENERAL_PRACTITIONER,
    CARDIOLOGIST,
    DERMATOLOGIST,
    NEUROLOGIST,
    ORTHOPEDIC_SURGEON,
    GASTROENTEROLOGIST,
    ENDOCRINOLOGIST,
    PULMONOLOGIST,
    GYNECOLOGIST,
    UROLOGIST,
    OPHTHALMOLOGIST,
    OTOLARYNGOLOGIST
}
